setwd("~/Documents/UCDavis/Whitehead/RNAseq_15killifish/DE_results")
# Get union of significant DE genes for all species (inclusive of all, regardless of unique or in common)
# FW
A_xenica_FW = read.csv("A_xenica_DE_TR_FW.csv")
A_xenica_DE = unique(A_xenica_FW$GeneID)
length(A_xenica_DE)
F_chrysotus_FW = read.csv("F_chrysotus_DE_TR_FW.csv")
F_chrysotus_DE = unique(F_chrysotus_FW$GeneID)
length(F_chrysotus_DE)
DE_genes = union(A_xenica_DE,F_chrysotus_DE)
length(DE_genes)
F_grandis_FW = read.csv("F_grandis_DE_TR_FW.csv")
F_grandis_DE = unique(F_grandis_FW$GeneID)
length(F_grandis_DE)
DE_genes = union(DE_genes,F_grandis_DE)
length(DE_genes)
F_heteroclitusMDPL_FW = read.csv("F_heteroclitusMDPL_DE_TR_FW.csv")
F_heteroclitusMDPL_DE = unique(F_heteroclitusMDPL_FW$GeneID)
length(F_heteroclitusMDPL_DE)
DE_genes = union(DE_genes,F_heteroclitusMDPL_DE)
length(DE_genes)
F_heteroclitusMDPP_FW = read.csv("F_heteroclitusMDPP_DE_TR_FW.csv")
F_heteroclitusMDPP_DE = unique(F_heteroclitusMDPP_FW$GeneID)
length(F_heteroclitusMDPP_DE)
DE_genes = union(DE_genes,F_heteroclitusMDPP_DE)
length(DE_genes)
F_notatus_FW = read.csv("F_notatus_DE_TR_FW.csv")
F_notatus_DE = unique(F_notatus_FW$GeneID)
length(F_notatus_DE)
DE_genes = union(DE_genes,F_notatus_DE)
length(DE_genes)
F_olivaceus_FW = read.csv("F_olivaceus_DE_TR_FW.csv")
F_olivaceus_DE = unique(F_olivaceus_FW$GeneID)
length(F_olivaceus_DE)
DE_genes = union(DE_genes,F_olivaceus_DE)
length(DE_genes)
F_parvapinis_FW = read.csv("F_parvapinis_DE_TR_FW.csv")
F_parvapinis_DE = unique(F_parvapinis_FW$GeneID)
length(F_parvapinis_DE)
DE_genes = union(DE_genes,F_parvapinis_DE)
length(DE_genes)
F_rathbuni_FW = read.csv("F_rathbuni_DE_TR_FW.csv")
F_rathbuni_DE = unique(F_rathbuni_FW$GeneID)
length(F_rathbuni_DE)
DE_genes = union(DE_genes,F_rathbuni_DE)
length(DE_genes)
F_similis_FW = read.csv("F_similis_DE_TR_FW.csv")
F_similis_DE = unique(F_similis_FW$GeneID)
length(F_similis_DE)
DE_genes = union(DE_genes,F_similis_DE)
length(DE_genes)
L_goodei_FW = read.csv("L_goodei_DE_TR_FW.csv")
L_goodei_DE = unique(L_goodei_FW$GeneID)
length(L_goodei_DE)
DE_genes = union(DE_genes,L_goodei_DE)
length(DE_genes)
L_parva_FW = read.csv("L_parva_DE_TR_FW.csv")
L_parva_DE = unique(L_parva_FW$GeneID)
length(L_parva_DE)
DE_genes = union(DE_genes,L_parva_DE)
length(DE_genes)
DE_genes_FW <- DE_genes
# BW
A_xenica_BW = read.csv("A_xenica_DE_TR_BW.csv")
A_xenica_DE = unique(A_xenica_BW$GeneID)
length(A_xenica_DE)
F_chrysotus_BW = read.csv("F_chrysotus_DE_TR_BW.csv")
F_chrysotus_DE = unique(F_chrysotus_BW$GeneID)
length(F_chrysotus_DE)
DE_genes = union(A_xenica_DE,F_chrysotus_DE)
length(DE_genes)
F_grandis_BW = read.csv("F_grandis_DE_TR_FW.csv")
F_grandis_DE = unique(F_grandis_BW$GeneID)
length(F_grandis_DE)
DE_genes = union(DE_genes,F_grandis_DE)
length(DE_genes)
F_heteroclitusMDPL_BW = read.csv("F_heteroclitusMDPL_DE_TR_BW.csv")
F_heteroclitusMDPL_DE = unique(F_heteroclitusMDPL_BW$GeneID)
length(F_heteroclitusMDPL_DE)
DE_genes = union(DE_genes,F_heteroclitusMDPL_DE)
length(DE_genes)
F_heteroclitusMDPP_BW = read.csv("F_heteroclitusMDPP_DE_TR_BW.csv")
F_heteroclitusMDPP_DE = unique(F_heteroclitusMDPP_BW$GeneID)
length(F_heteroclitusMDPP_DE)
DE_genes = union(DE_genes,F_heteroclitusMDPP_DE)
length(DE_genes)
F_notatus_BW = read.csv("F_notatus_DE_TR_FW.csv")
F_notatus_DE = unique(F_notatus_BW$GeneID)
length(F_notatus_DE)
DE_genes = union(DE_genes,F_notatus_DE)
length(DE_genes)
F_olivaceus_BW = read.csv("F_olivaceus_DE_TR_BW.csv")
F_olivaceus_DE = unique(F_olivaceus_BW$GeneID)
length(F_olivaceus_DE)
DE_genes = union(DE_genes,F_olivaceus_DE)
length(DE_genes)
F_parvapinis_BW = read.csv("F_parvapinis_DE_TR_BW.csv")
F_parvapinis_DE = unique(F_parvapinis_BW$GeneID)
length(F_parvapinis_DE)
DE_genes = union(DE_genes,F_parvapinis_DE)
length(DE_genes)
F_rathbuni_BW = read.csv("F_rathbuni_DE_TR_FW.csv")
F_rathbuni_DE = unique(F_rathbuni_BW$GeneID)
length(F_rathbuni_DE)
DE_genes = union(DE_genes,F_rathbuni_DE)
length(DE_genes)
F_similis_BW = read.csv("F_similis_DE_TR_BW.csv")
F_similis_DE = unique(F_similis_BW$GeneID)
length(F_similis_DE)
DE_genes = union(DE_genes,F_similis_DE)
length(DE_genes)
L_goodei_BW = read.csv("L_goodei_DE_TR_BW.csv")
L_goodei_DE = unique(L_goodei_BW$GeneID)
length(L_goodei_DE)
DE_genes = union(DE_genes,L_goodei_DE)
length(DE_genes)
L_parva_BW = read.csv("L_parva_DE_TR_BW.csv")
L_parva_DE = unique(L_parva_BW$GeneID)
length(L_parva_DE)
DE_genes = union(DE_genes,L_parva_DE)
length(DE_genes)
DE_genes_BW <- DE_genes
# ALL DE
setwd("~/Documents/UCDavis/Whitehead/DE_results_all_genes")
A_xenica_all = read.csv("A_xenica_DE_all.csv")
A_xenica_DE <- A_xenica_all[A_xenica_all$GeneID %in% DE_genes_FW,]
dim(A_xenica_DE)
A_xenica_DE <- A_xenica_DE[!duplicated(A_xenica_DE$GeneID),]
dim(A_xenica_DE)
F_chrysotus_all = read.csv("F_chrysotus_DE_all.csv")
F_chrysotus_DE <- F_chrysotus_all[F_chrysotus_all$GeneID %in% DE_genes_FW,]
dim(F_chrysotus_DE)
F_chrysotus_DE <- F_chrysotus_DE[!duplicated(F_chrysotus_DE$GeneID),]
dim(F_chrysotus_DE)
F_grandis_all = read.csv("F_grandis_DE_all.csv")
F_grandis_DE = F_grandis_all[F_grandis_all$GeneID %in% DE_genes_FW,]
dim(F_grandis_DE)
F_grandis_DE = F_grandis_DE[!duplicated(F_grandis_DE$GeneID),]
dim(F_grandis_DE)
F_heteroclitusMDPL_all = read.csv("F_heteroclitusMDPL_DE_all.csv")
F_heteroclitusMDPP_all = read.csv("F_heteroclitusMDPP_DE_all.csv")
F_notatus_all = read.csv("F_notatus_DE_all.csv")
F_olivaceus_all = read.csv("F_olivaceus_DE_all.csv")
F_parvapinis_all = read.csv("F_parvapinis_DE_all.csv")
F_rathbuni_all = read.csv("F_rathbuni_DE_all.csv")
F_similis_all = read.csv("F_similis_DE_all.csv")
L_goodei_all = read.csv("L_goodei_DE_all.csv")
L_parva_all = read.csv("L_parva_DE_all.csv")
# Combine all FW
