---
title: "RNAseq, multispecies killifish osmotic challenge"
author: "Lisa K. Johnson"
date: '`r Sys.Date()`'
output:
  html_document:
    code_folding: hide
    collapsed: no
    df_print: paged
    number_sections: yes
    theme: cerulean
    toc: yes
    toc_depth: 5
    toc_float: yes
---

```{r LoadPackages, results='hide', include=FALSE}
# Install function for packages    
packages<-function(x){
  x<-as.character(match.call()[[2]])
  if (!require(x,character.only=TRUE)){
    install.packages(pkgs=x,repos="http://cran.r-project.org")
    require(x,character.only=TRUE)
  }
}
bioconductors <- function(x){
    x<- as.character(match.call()[[2]])
    if (!require(x, character.only = TRUE)){
      source("https://bioconductor.org/biocLite.R")
      biocLite(pkgs=x)
      require(x, character.only = TRUE)
    }
}
# for QC
packages("RColorBrewer")
packages("pheatmap")
packages("vsn")
packages(pheatmap)
packages(cowplot)
# for DESeq
packages(lattice)
packages(RColorBrewer)
packages(dplyr)
packages(tidyr)
packages(gplots)
packages(ggplot2)
packages(gridExtra)
bioconductors(DESeq2)
bioconductors(tximport)
bioconductors(biomaRt)
```


```{r load custom scripts and data, results='hide', include=FALSE}
if(!file.exists('plotPCAWithSampleNames.R')){
  download.file('https://gist.githubusercontent.com/ljcohen/d6cf3367efae60d7fa1ea383fd7a1296/raw/f11030ced8c7953be6fada0325b92c20d369e0a7/plotPCAWithSampleNames.R', 'plotPCAWithSampleNames.R')
  }
source('plotPCAWithSampleNames.R')
if(!file.exists('overLapper_original.R')){
  download.file("https://gist.githubusercontent.com/ljcohen/b7e5fa93b8b77c33d26e4c44cadb5bb7/raw/3a2f84be2e937ef721cafaf308ff6456168f30d9/overLapper_original.R",'overLapper_original.R')
}
source('overLapper_original.R')
# This is just the counts with Experimental Design Info in the last 5 rows
if(!file.exists('../../Ensembl_species_counts_designfactors.csv')){
  download.file("https://osf.io/7vp38/download",'../../Ensembl_species_counts_designfactors.csv')
}
counts_design <- read.csv("../../Ensembl_species_counts_designfactors.csv",stringsAsFactors = FALSE)
```


```{r format counts and ExpDesign, include=FALSE, results='hide'}
design <- counts_design[counts_design$Ensembl == 'Empty',]
#design$type <- c("species","native_salinity","clade","group","condition")
drops <- c("X","Ensembl")
counts<-counts_design[!counts_design$Ensembl == 'Empty',]
rownames(counts)<-counts$Ensembl
design <- design[ , !(names(design) %in% drops)]
counts <- counts[ , !(names(counts) %in% drops)]
dim(design)
dim(counts)
```

```{r design for DESeq, results='hide', include=FALSE}
# design cateogories (full)
species<-as.character(unlist(design[1,]))
physiology<-as.character(unlist(design[2,]))
clade<-as.character(unlist(design[3,]))
np_cl<-as.character(unlist(design[4,]))
condition<-as.character(unlist(design[5,]))
species_physiology<-as.vector(paste(np_cl, species, sep="_"))
species_condition<-as.vector(paste(species,condition,sep="_"))
species_group<-as.vector(paste(np_cl,species,sep="_"))
species_clade<-as.vector(paste(clade,species,sep="_"))
```

At least 64 samples have a count of at least 0.01:

```{r filtering12,}
filter <- rownames(counts[rowSums(counts >= 0.01) >= 64,])
filtered_counts <- counts[filter,]
dim(filtered_counts)
```

# DESeq analysis

Design

```{r DESeq2 design,}
cols<-colnames(counts)
ExpDesign <- data.frame(row.names=cols, physiology=physiology,condition=condition, species = species, clade=clade,species_condition=species_condition,species_clade = species_clade)
ExpDesign
```

Clade1_F_catanatus and 0.2 ppt are reference levels for comparison.

```
m1 <- model.matrix(~condition + species_clade + species_clade:condition,ExpDesign)
```

```{r DESeq2 filter design for missing samples, results='hide', include=FALSE}
m1 <- model.matrix(~condition + species_clade + species_clade:condition,ExpDesign)
#colnames(m1)
all.zero <- apply(m1, 2, function(x) all(x==0))
idx <- which(all.zero)
m1 <- m1[,-idx]
```

```{r run DESeq2,results='hide', include=FALSE}
counts_round<- round(data.matrix(filtered_counts),digits=0)
#dds <- DESeqDataSetFromMatrix(countData = counts_round,colData = ExpDesign,design = m1)
#dds <- DESeq(dds, full = m1, betaPrior=FALSE)
#ddsClean <- dds[which(mcols(dds)$betaConv),]
#dds<-ddsClean
counts_table <- read.csv("../../killifish_counts_filtered_64samples0.01.csv")
load("../../dds_interactionConditionSpecies.RData")
```

```{r get annotated counts tables,results='hide', include=FALSE}
# load counts, stats, annotation tables
Fcat_counts_table_ann <- read.csv("../../counts_stats_byspecies/Fcat_stats_annotations_counts.csv",row.names = 1)
Fdia_counts_table_ann <- read.csv("../../counts_stats_byspecies/Fdiaphanus_stats_annotations_counts.csv",row.names = 1)
Fgran_counts_table_ann <- read.csv("../../counts_stats_byspecies/Fgrandis_stats_annotations_counts.csv",row.names = 1)
FhetMDPL_counts_table_ann <- read.csv("../../counts_stats_byspecies/FheteroclitusMDPL_stats_annotations_counts.csv",row.names = 1)
FhetMDPP_counts_table_ann <- read.csv("../../counts_stats_byspecies/FheteroclitusMDPP_stats_annotations_counts.csv",row.names = 1)
Frath_counts_table_ann <- read.csv("../../counts_stats_byspecies/Frathbuni_stats_annotations_counts.csv",row.names = 1)
Fsim_counts_table_ann <- read.csv("../../counts_stats_byspecies/Fsimils_stats_annotations_counts.csv",row.names = 1)
Fparv_counts_table_ann <- read.csv("../../counts_stats_byspecies/Fparvapinis_stats_annotations_counts.csv",row.names = 1)
Lgod_counts_table_ann <- read.csv("../../counts_stats_byspecies/Lgoodei_stats_annotations_counts.csv",row.names = 1)
Lpar_counts_table_ann <- read.csv("../../counts_stats_byspecies/Lparva_stats_annotations_counts.csv",row.names = 1)
Axen_counts_table_ann <- read.csv("../../counts_stats_byspecies/Axenica_stats_annotations_counts.csv",row.names = 1)
Fchry_counts_table_ann <- read.csv("../../counts_stats_byspecies/Fchrysotus_stats_annotations_counts.csv",row.names = 1)
Fnota_counts_table_ann <- read.csv("../../counts_stats_byspecies/Fnotatus_stats_annotations_counts.csv",row.names = 1)
Foli_counts_table_ann <- read.csv("../../counts_stats_byspecies/Folivaceus_stats_annotations_counts.csv",row.names = 1)
Fsci_counts_table_ann <- read.csv("../../counts_stats_byspecies/Fsciadicus_stats_annotations_counts.csv",row.names = 1)
Fzeb_counts_table_ann <- read.csv("../../counts_stats_byspecies/Fzebrinus_stats_annotations_counts.csv",row.names = 1)
# Clade 1
Fcat_counts_table_ann_sig <- subset(Fcat_counts_table_ann,Fcat_counts_table_ann$`padj-15ppt-v-0.2ppt`<0.05)
Fcat_counts_table_ann_up <- subset(Fcat_counts_table_ann_sig,Fcat_counts_table_ann_sig$`log2FoldChange-15ppt-v-0.2ppt` > 0.5)
Fcat_counts_table_ann_down <- subset(Fcat_counts_table_ann_sig,Fcat_counts_table_ann_sig$`log2FoldChange-15ppt-v-0.2ppt` < -0.5)
#dim(Fcat_counts_table_ann_sig)
Fdia_counts_table_ann_sig <- subset(Fdia_counts_table_ann,Fdia_counts_table_ann$`padj-15ppt-v-0.2ppt`<0.05)
Fdia_counts_table_ann_up <- subset(Fdia_counts_table_ann_sig,Fdia_counts_table_ann_sig$`log2FoldChange-15ppt-v-0.2ppt` > 0.5)
Fdia_counts_table_ann_down <- subset(Fdia_counts_table_ann_sig,Fdia_counts_table_ann_sig$`log2FoldChange-15ppt-v-0.2ppt` < -0.5)
#dim(Fdia_counts_table_ann_sig)
Fgran_counts_table_ann_sig <- subset(Fgran_counts_table_ann,Fgran_counts_table_ann$`padj-15ppt-v-0.2ppt`<0.05)
Fgran_counts_table_ann_up <- subset(Fgran_counts_table_ann_sig,Fgran_counts_table_ann_sig$`log2FoldChange-15ppt-v-0.2ppt` > 0.5)
Fgran_counts_table_ann_down <- subset(Fgran_counts_table_ann_sig,Fgran_counts_table_ann_sig$`log2FoldChange-15ppt-v-0.2ppt` < -0.5)
#dim(Fgran_counts_table_ann_sig)
FhetMDPL_counts_table_ann_sig <- subset(FhetMDPL_counts_table_ann,FhetMDPL_counts_table_ann$`padj-15ppt-v-0.2ppt`<0.05)
FhetMDPL_counts_table_ann_up <- subset(FhetMDPL_counts_table_ann_sig,FhetMDPL_counts_table_ann_sig$`log2FoldChange-15ppt-v-0.2ppt` > 0.5)
FhetMDPL_counts_table_ann_down <- subset(FhetMDPL_counts_table_ann_sig,FhetMDPL_counts_table_ann_sig$`log2FoldChange-15ppt-v-0.2ppt` < -0.5)
#dim(FhetMDPL_counts_table_ann_sig)
FhetMDPP_counts_table_ann_sig <- subset(FhetMDPP_counts_table_ann,FhetMDPP_counts_table_ann$`padj-15ppt-v-0.2ppt`<0.05)
FhetMDPP_counts_table_ann_up <- subset(FhetMDPP_counts_table_ann_sig,FhetMDPP_counts_table_ann_sig$`log2FoldChange-15ppt-v-0.2ppt` > 0.5)
FhetMDPP_counts_table_ann_down <- subset(FhetMDPP_counts_table_ann_sig,FhetMDPP_counts_table_ann_sig$`log2FoldChange-15ppt-v-0.2ppt` < -0.5)
#dim(FhetMDPP_counts_table_ann_sig)
Frath_counts_table_ann_sig <- subset(Frath_counts_table_ann,Frath_counts_table_ann$`padj-15ppt-v-0.2ppt`<0.05)
Frath_counts_table_ann_up <- subset(Frath_counts_table_ann_sig,Frath_counts_table_ann_sig$`log2FoldChange-15ppt-v-0.2ppt` > 0.5)
Frath_counts_table_ann_down <- subset(Frath_counts_table_ann_sig,Frath_counts_table_ann_sig$`log2FoldChange-15ppt-v-0.2ppt` < -0.5)
#dim(Frath_counts_table_ann_sig)
Fsim_counts_table_ann_sig <- subset(Fsim_counts_table_ann,Fsim_counts_table_ann$`padj-15ppt-v-0.2ppt`<0.05)
Fsim_counts_table_ann_up <- subset(Fsim_counts_table_ann_sig,Fsim_counts_table_ann_sig$`log2FoldChange-15ppt-v-0.2ppt` > 0.5)
Fsim_counts_table_ann_down <- subset(Fsim_counts_table_ann_sig,Fsim_counts_table_ann_sig$`log2FoldChange-15ppt-v-0.2ppt` < -0.5)
#dim(Fsim_counts_table_ann_sig)
# Clade 2
Fparv_counts_table_ann_sig <- subset(Fparv_counts_table_ann,Fparv_counts_table_ann$`padj-15ppt-v-0.2ppt`<0.05)
Fparv_counts_table_ann_up <- subset(Fparv_counts_table_ann_sig,Fparv_counts_table_ann_sig$`log2FoldChange-15ppt-v-0.2ppt` > 0.5)
Fparv_counts_table_ann_down <- subset(Fparv_counts_table_ann_sig,Fparv_counts_table_ann_sig$`log2FoldChange-15ppt-v-0.2ppt` < -0.5)
#dim(Fparv_counts_table_ann_sig)
Lgod_counts_table_ann_sig <- subset(Lgod_counts_table_ann,Lgod_counts_table_ann$`padj-15ppt-v-0.2ppt`<0.05)
Lgod_counts_table_ann_up <- subset(Lgod_counts_table_ann_sig,Lgod_counts_table_ann_sig$`log2FoldChange-15ppt-v-0.2ppt` > 0.5)
Lgod_counts_table_ann_down <- subset(Lgod_counts_table_ann_sig,Lgod_counts_table_ann_sig$`log2FoldChange-15ppt-v-0.2ppt` < -0.5)
#dim(Lgod_counts_table_ann_sig)
Lpar_counts_table_ann_sig <- subset(Lpar_counts_table_ann,Lpar_counts_table_ann$`padj-15ppt-v-0.2ppt`<0.05)
Lpar_counts_table_ann_up <- subset(Lpar_counts_table_ann_sig,Lpar_counts_table_ann_sig$`log2FoldChange-15ppt-v-0.2ppt` > 0.5)
Lpar_counts_table_ann_down <- subset(Lpar_counts_table_ann_sig,Lpar_counts_table_ann_sig$`log2FoldChange-15ppt-v-0.2ppt` < -0.5)
#dim(Lpar_counts_table_ann_sig)
# Clade 3
Axen_counts_table_ann_sig <- subset(Axen_counts_table_ann,Axen_counts_table_ann$`padj-15ppt-v-0.2ppt`<0.05)
Axen_counts_table_ann_up <- subset(Axen_counts_table_ann_sig,Axen_counts_table_ann_sig$`log2FoldChange-15ppt-v-0.2ppt` > 0.5)
Axen_counts_table_ann_down <- subset(Axen_counts_table_ann_sig,Axen_counts_table_ann_sig$`log2FoldChange-15ppt-v-0.2ppt` < -0.5)
#dim(Axen_counts_table_ann_sig)
Fchry_counts_table_ann_sig <- subset(Fchry_counts_table_ann,Fchry_counts_table_ann$`padj-15ppt-v-0.2ppt`<0.05)
Fchry_counts_table_ann_up <- subset(Fchry_counts_table_ann_sig,Fchry_counts_table_ann_sig$`log2FoldChange-15ppt-v-0.2ppt` > 0.5)
Fchry_counts_table_ann_down <- subset(Fchry_counts_table_ann_sig,Fchry_counts_table_ann_sig$`log2FoldChange-15ppt-v-0.2ppt` < -0.5)
#dim(Fchry_counts_table_ann_sig)
Fnota_counts_table_ann_sig <- subset(Fnota_counts_table_ann,Fnota_counts_table_ann$`padj-15ppt-v-0.2ppt`<0.05)
Fnota_counts_table_ann_up <- subset(Fnota_counts_table_ann_sig,Fnota_counts_table_ann_sig$`log2FoldChange-15ppt-v-0.2ppt` > 0.5)
Fnota_counts_table_ann_down <- subset(Fnota_counts_table_ann_sig,Fnota_counts_table_ann_sig$`log2FoldChange-15ppt-v-0.2ppt` < -0.5)
#dim(Fnota_counts_table_ann_sig)
Foli_counts_table_ann_sig <- subset(Foli_counts_table_ann,Foli_counts_table_ann$`padj-15ppt-v-0.2ppt`<0.05)
Foli_counts_table_ann_up <- subset(Foli_counts_table_ann_sig,Foli_counts_table_ann_sig$`log2FoldChange-15ppt-v-0.2ppt` > 0.5)
Foli_counts_table_ann_down <- subset(Foli_counts_table_ann_sig,Foli_counts_table_ann_sig$`log2FoldChange-15ppt-v-0.2ppt` < -0.5)
#dim(Foli_counts_table_ann_sig)
Fsci_counts_table_ann_sig <- subset(Fsci_counts_table_ann,Fsci_counts_table_ann$`padj-15ppt-v-0.2ppt`<0.05)
Fsci_counts_table_ann_up <- subset(Fsci_counts_table_ann_sig,Fsci_counts_table_ann_sig$`log2FoldChange-15ppt-v-0.2ppt` > 0.5)
Fsci_counts_table_ann_down <- subset(Fsci_counts_table_ann_sig,Fsci_counts_table_ann_sig$`log2FoldChange-15ppt-v-0.2ppt` < -0.5)
#dim(Fsci_counts_table_ann_sig)
Fzeb_counts_table_ann_sig <- subset(Fzeb_counts_table_ann,Fzeb_counts_table_ann$`padj-15ppt-v-0.2ppt`<0.05)
Fzeb_counts_table_ann_up <- subset(Fzeb_counts_table_ann_sig,Fzeb_counts_table_ann_sig$`log2FoldChange-15ppt-v-0.2ppt` > 0.5)
Fzeb_counts_table_ann_down <- subset(Fzeb_counts_table_ann_sig,Fzeb_counts_table_ann_sig$`log2FoldChange-15ppt-v-0.2ppt` < -0.5)
#dim(Fzeb_counts_table_ann_sig)
```

```{r set column names,results='hide', include=FALSE}
# column names for each species
# clade1
Fcat_TR_cols <- c("F_catanatus_transfer_1.quant","F_catanatus_transfer_2.quant")
Fcat_FW_cols <- c("F_catanatus_FW_1.quant","F_catanatus_FW_2.quant")
Fcat_BW_cols <- c("F_catanatus_BW_1.quant","F_catanatus_BW_2.quant","F_catanatus_BW_3.quant")
Fdia_FW_cols <- c("F_diaphanus_FW_2.quant", "F_diaphanus_FW_3.quant")
Fdia_TR_cols <- c("F_diaphanus_transfer_1.quant","F_diaphanus_transfer_2.quant")
Fdia_BW_cols <- c("F_diaphanus_BW_1.quant", "F_diaphanus_BW_2.quant")
Fgran_FW_cols <- c("F_grandis_FW_1.quant", "F_grandis_FW_2.quant", "F_grandis_FW_3.quant")
Fgran_TR_cols <- c("F_grandis_transfer_1.quant", "F_grandis_transfer_2.quant", "F_grandis_transfer_3.quant")
Fgran_BW_cols <- c("F_grandis_BW_1.quant", "F_grandis_BW_2.quant", "F_grandis_BW_3.quant")
FhetMDPL_FW_cols <- c("F_heteroclitusMDPL_FW_1.quant", "F_heteroclitusMDPL_FW_2.quant", "F_heteroclitusMDPL_FW_3.quant")
FhetMDPL_TR_cols <- c("F_heteroclitusMDPL_transfer_1.quant", "F_heteroclitusMDPL_transfer_2.quant", "F_heteroclitusMDPL_transfer_3.quant")
FhetMDPL_BW_cols <- c("F_heteroclitusMDPL_BW_1.quant" , "F_heteroclitusMDPL_BW_2.quant" , "F_heteroclitusMDPL_BW_3.quant")
FhetMDPP_BW_cols <- c("F_heteroclitusMDPP_BW_1.quant" , "F_heteroclitusMDPP_BW_2.quant" , "F_heteroclitusMDPP_BW_3.quant")
FhetMDPP_FW_cols <- c("F_heteroclitusMDPP_FW_1.quant", "F_heteroclitusMDPP_FW_2.quant", "F_heteroclitusMDPP_FW_3.quant")
FhetMDPP_TR_cols <- c("F_heteroclitusMDPP_transfer_1.quant", "F_heteroclitusMDPP_transfer_2.quant", "F_heteroclitusMDPP_transfer_3.quant")
Frath_BW_cols <- c("F_rathbuni_BW_1.quant","F_rathbuni_BW_2.quant","F_rathbuni_BW_3.quant")
Frath_FW_cols <- c("F_rathbuni_FW_1.quant","F_rathbuni_FW_2.quant","F_rathbuni_FW_3.quant")
Frath_TR_cols <- c("F_rathbuni_transfer_1.quant","F_rathbuni_transfer_2.quant","F_rathbuni_transfer_3.quant")
Fsim_BW_cols <- c("F_similis_BW_1.quant","F_similis_BW_2.quant","F_similis_BW_3.quant")
Fsim_FW_cols <- c("F_similis_FW_1.quant","F_similis_FW_2.quant","F_similis_FW_3.quant")
Fsim_TR_cols <- c("F_similis_transfer_1.quant","F_similis_transfer_2.quant","F_similis_transfer_3.quant")
#clade2
Fparv_BW_cols <- c("F_parvapinis_BW_1.quant","F_parvapinis_BW_2.quant","F_parvapinis_BW_3.quant")
Fparv_FW_cols <- c("F_parvapinis_FW_1.quant","F_parvapinis_FW_2.quant","F_parvapinis_FW_3.quant")
Fparv_TR_cols <- c("F_parvapinis_transfer_1.quant","F_parvapinis_transfer_2.quant")
Lgod_BW_cols <- c("L_goodei_BW_1.quant","L_goodei_BW_2.quant","L_goodei_BW_3.quant")
Lgod_FW_cols <- c("L_goodei_FW_1.quant","L_goodei_FW_2.quant","L_goodei_FW_3.quant")
Lgod_TR_cols <- c("L_goodei_transfer_1.quant","L_goodei_transfer_2.quant","L_goodei_transfer_3.quant")
Lpar_BW_cols <- c("L_parva_BW_1.quant","L_parva_BW_2.quant","L_parva_BW_3.quant")
Lpar_FW_cols <- c("L_parva_FW_1.quant","L_parva_FW_2.quant","L_parva_FW_3.quant")
Lpar_TR_cols <- c("L_parva_transfer_1.quant","L_parva_transfer_2.quant","L_parva_transfer_3.quant")
# clade 3
Axen_BW_cols <- c("A_xenica_BW_1.quant","A_xenica_BW_2.quant","A_xenica_BW_3.quant")
Axen_FW_cols <- c("A_xenica_FW_1.quant","A_xenica_FW_2.quant","A_xenica_FW_3.quant")
Axen_TR_cols <- c("A_xenica_transfer_1.quant","A_xenica_transfer_2.quant","A_xenica_transfer_3.quant")
Fchry_BW_cols <- c("F_chrysotus_BW_1.quant","F_chrysotus_BW_2.quant","F_chrysotus_BW_3.quant")
Fchry_FW_cols <- c("F_chrysotus_FW_1.quant","F_chrysotus_FW_2.quant","F_chrysotus_FW_3.quant")
Fchry_TR_cols <- c("F_chrysotus_transfer_1.quant","F_chrysotus_transfer_2.quant")
Fnota_BW_cols <- c("F_notatus_BW_1.quant","F_notatus_BW_2.quant","F_notatus_BW_3.quant")
Fnota_FW_cols <- c("F_notatus_FW_1.quant","F_notatus_FW_2.quant","F_notatus_FW_3.quant")
Fnota_TR_cols <- c("F_notatus_transfer_1.quant","F_notatus_transfer_2.quant","F_notatus_transfer_3.quant")
Foli_BW_cols <- c("F_olivaceous_BW_1.quant","F_olivaceous_BW_2.quant","F_olivaceous_BW_3.quant")
Foli_FW_cols <- c("F_olivaceous_FW_1.quant","F_olivaceous_FW_2.quant","F_olivaceous_FW_3.quant")
Foli_TR_cols <- c("F_olivaceous_transfer_1.quant","F_olivaceous_transfer_2.quant")
Fsci_BW_cols <- c("F_sciadicus_BW_1.quant")
Fsci_FW_cols <- c("F_sciadicus_FW_1.quant","F_sciadicus_FW_2.quant")
Fsci_TR_cols <- c("F_sciadicus_transfer_1.quant")
Fzeb_BW_cols <- c("F_zebrinus_BW_1.quant","F_zebrinus_BW_2.quant")
Fzeb_FW_cols <- c("F_zebrinus_FW_1.quant","F_zebrinus_FW_2.quant")
counts_table = counts(dds, normalized=TRUE)
```

# Clade 1 Heatmaps

```{r F. catanatus heatmap,}
#Fcat_cols <- c(Fcat_FW_cols,Fcat_BW_cols)
#Fcat_counts <- counts_table[rownames(counts_table) %in% rownames(Fcat_counts_table_ann_up),]
#Fcat_counts <- Fcat_counts[,Fcat_cols]
#id <-rownames(Fcat_counts)
#d<-as.matrix(Fcat_counts)
#hr <- hclust(as.dist(1-cor(t(d), method="pearson")), method="complete")
#mycl <- cutree(hr, h=max(hr$height/1.5))
#clusterCols <- rainbow(length(unique(mycl)))
#myClusterSideBar <- clusterCols[mycl]
#myheatcol <- greenred(75)
#heatmap.2(d, main="F. catanatus, FC > 0.5, common sig genes (padj<0.05)",
#          Rowv=as.dendrogram(hr),
#          cexRow=0.75,cexCol=0.8,srtCol= 90,
#          adjCol = c(NA,0),offsetCol=2.5, 
#          Colv=NA, dendrogram="row", 
#          scale="row", col=myheatcol, 
#          density.info="none", 
#          trace="none", RowSideColors= myClusterSideBar)
#Fcat_counts <- counts_table[rownames(counts_table) %in% rownames(Fcat_counts_table_ann_down),]
#Fcat_counts <- Fcat_counts[,Fcat_cols]
#id <-rownames(Fcat_counts)
#d<-as.matrix(Fcat_counts)
#hr <- hclust(as.dist(1-cor(t(d), method="pearson")), method="complete")
#mycl <- cutree(hr, h=max(hr$height/1.5))
#clusterCols <- rainbow(length(unique(mycl)))
#myClusterSideBar <- clusterCols[mycl]
#myheatcol <- greenred(75)
#heatmap.2(d, main="F. catanatus, FC < 0.5, common sig genes (padj<0.05)",
#          Rowv=as.dendrogram(hr),
#          cexRow=0.75,cexCol=0.8,srtCol= 90,
#          adjCol = c(NA,0),offsetCol=2.5, 
#          Colv=NA, dendrogram="row", 
#          scale="row", col=myheatcol, 
#          density.info="none", 
#          trace="none", RowSideColors= myClusterSideBar)
```


```{r F. diaphanus heatmap,}
# F. diaphanus
Fdia_cols <- c(Fdia_FW_cols,Fdia_BW_cols)
Fdia_counts <- counts_table[rownames(counts_table) %in% rownames(Fdia_counts_table_ann_up),]
Fdia_counts <- Fdia_counts[,Fdia_cols]
id <-rownames(Fdia_counts)
d<-as.matrix(Fdia_counts)
hr <- hclust(as.dist(1-cor(t(d), method="pearson")), method="complete")
mycl <- cutree(hr, h=max(hr$height/1.5))
clusterCols <- rainbow(length(unique(mycl)))
myClusterSideBar <- clusterCols[mycl]
myheatcol <- greenred(75)
heatmap.2(d, main="F. diaphanus, FC > 0.5, common sig genes (padj<0.05)",
          Rowv=as.dendrogram(hr),
          cexRow=0.75,cexCol=0.8,srtCol= 90,
          adjCol = c(NA,0),offsetCol=2.5, 
          Colv=NA, dendrogram="row", 
          scale="row", col=myheatcol, 
          density.info="none", 
          trace="none", RowSideColors= myClusterSideBar)
Fdia_counts <- counts_table[rownames(counts_table) %in% rownames(Fdia_counts_table_ann_down),]
Fdia_counts <- Fdia_counts[,Fdia_cols]
id <-rownames(Fdia_counts)
d<-as.matrix(Fdia_counts)
hr <- hclust(as.dist(1-cor(t(d), method="pearson")), method="complete")
mycl <- cutree(hr, h=max(hr$height/1.5))
clusterCols <- rainbow(length(unique(mycl)))
myClusterSideBar <- clusterCols[mycl]
myheatcol <- greenred(75)
heatmap.2(d, main="F. diaphanus, FC < 0.5, common sig genes (padj<0.05)",
          Rowv=as.dendrogram(hr),
          cexRow=0.75,cexCol=0.8,srtCol= 90,
          adjCol = c(NA,0),offsetCol=2.5, 
          Colv=NA, dendrogram="row", 
          scale="row", col=myheatcol, 
          density.info="none", 
          trace="none", RowSideColors= myClusterSideBar)
```

```{r F. grandis heatmap,}
# F. grandis
Fgran_cols <- c(Fgran_FW_cols,Fgran_BW_cols)
Fgran_counts <- counts_table[rownames(counts_table) %in% rownames(Fgran_counts_table_ann_up ),]
Fgran_counts <- Fgran_counts[,Fgran_cols]
id <-rownames(Fgran_counts)
d<-as.matrix(Fgran_counts)
hr <- hclust(as.dist(1-cor(t(d), method="pearson")), method="complete")
mycl <- cutree(hr, h=max(hr$height/1.5))
clusterCols <- rainbow(length(unique(mycl)))
myClusterSideBar <- clusterCols[mycl]
myheatcol <- greenred(75)
heatmap.2(d, main="F. grandis, FC > 0.5, common sig genes (padj<0.05)",
          Rowv=as.dendrogram(hr),
          cexRow=0.75,cexCol=0.8,srtCol= 90,
          adjCol = c(NA,0),offsetCol=2.5, 
          Colv=NA, dendrogram="row", 
          scale="row", col=myheatcol, 
          density.info="none", 
          trace="none", RowSideColors= myClusterSideBar)
Fgran_counts <- counts_table[rownames(counts_table) %in% rownames(Fgran_counts_table_ann_down),]
Fgran_counts <- Fgran_counts[,Fgran_cols]
id <-rownames(Fgran_counts)
d<-as.matrix(Fgran_counts)
hr <- hclust(as.dist(1-cor(t(d), method="pearson")), method="complete")
mycl <- cutree(hr, h=max(hr$height/1.5))
clusterCols <- rainbow(length(unique(mycl)))
myClusterSideBar <- clusterCols[mycl]
myheatcol <- greenred(75)
heatmap.2(d, main="F. diaphanus, FC < 0.5, common sig genes (padj<0.05)",
          Rowv=as.dendrogram(hr),
          cexRow=0.75,cexCol=0.8,srtCol= 90,
          adjCol = c(NA,0),offsetCol=2.5, 
          Colv=NA, dendrogram="row", 
          scale="row", col=myheatcol, 
          density.info="none", 
          trace="none", RowSideColors= myClusterSideBar)
```

```{r F. heteroclitus MDPL population heatmap,}
# F. heteroclitus MDPL population
FhetMDPL_cols <- c(FhetMDPL_FW_cols,FhetMDPL_BW_cols)
FhetMDPL_counts <- counts_table[rownames(counts_table) %in% rownames(FhetMDPL_counts_table_ann_up),]
FhetMDPL_counts <- FhetMDPL_counts[,FhetMDPL_cols]
id <-rownames(FhetMDPL_counts)
d<-as.matrix(FhetMDPL_counts)
hr <- hclust(as.dist(1-cor(t(d), method="pearson")), method="complete")
mycl <- cutree(hr, h=max(hr$height/1.5))
clusterCols <- rainbow(length(unique(mycl)))
myClusterSideBar <- clusterCols[mycl]
myheatcol <- greenred(75)
heatmap.2(d, main="F. heteroclitus (MDPL population), FC > 0.5, common sig genes (padj<0.05)",
          Rowv=as.dendrogram(hr),
          cexRow=0.75,cexCol=0.8,srtCol= 90,
          adjCol = c(NA,0),offsetCol=2.5, 
          Colv=NA, dendrogram="row", 
          scale="row", col=myheatcol, 
          density.info="none", 
          trace="none", RowSideColors= myClusterSideBar)
FhetMDPL_counts <- counts_table[rownames(counts_table) %in% rownames(FhetMDPL_counts_table_ann_down),]
FhetMDPL_counts <- FhetMDPL_counts[,FhetMDPL_cols]
id <-rownames(FhetMDPL_counts)
d<-as.matrix(FhetMDPL_counts)
hr <- hclust(as.dist(1-cor(t(d), method="pearson")), method="complete")
mycl <- cutree(hr, h=max(hr$height/1.5))
clusterCols <- rainbow(length(unique(mycl)))
myClusterSideBar <- clusterCols[mycl]
myheatcol <- greenred(75)
heatmap.2(d, main="F. heteroclitus (MDPL population), FC < 0.5, common sig genes (padj<0.05)",
          Rowv=as.dendrogram(hr),
          cexRow=0.75,cexCol=0.8,srtCol= 90,
          adjCol = c(NA,0),offsetCol=2.5, 
          Colv=NA, dendrogram="row", 
          scale="row", col=myheatcol, 
          density.info="none", 
          trace="none", RowSideColors= myClusterSideBar)
```


```{r F. heteroclitus MDPP population heatmap,}
# F. heteroclitus MDPP population
FhetMDPP_cols <- c(FhetMDPP_FW_cols,FhetMDPP_BW_cols)
FhetMDPP_counts <- counts_table[rownames(counts_table) %in% rownames(FhetMDPP_counts_table_ann_up),]
FhetMDPP_counts <- FhetMDPL_counts[,FhetMDPL_cols]
id <-rownames(FhetMDPP_counts)
d<-as.matrix(FhetMDPP_counts)
hr <- hclust(as.dist(1-cor(t(d), method="pearson")), method="complete")
mycl <- cutree(hr, h=max(hr$height/1.5))
clusterCols <- rainbow(length(unique(mycl)))
myClusterSideBar <- clusterCols[mycl]
myheatcol <- greenred(75)
heatmap.2(d, main="F. heteroclitus (MDPP population), FC > 0.5, common sig genes (padj<0.05)",
          Rowv=as.dendrogram(hr),
          cexRow=0.75,cexCol=0.8,srtCol= 90,
          adjCol = c(NA,0),offsetCol=2.5, 
          Colv=NA, dendrogram="row", 
          scale="row", col=myheatcol, 
          density.info="none", 
          trace="none", RowSideColors= myClusterSideBar)
FhetMDPP_counts <- counts_table[rownames(counts_table) %in% rownames(FhetMDPP_counts_table_ann_down),]
FhetMDPP_counts <- FhetMDPP_counts[,FhetMDPP_cols]
id <-rownames(FhetMDPP_counts)
d<-as.matrix(FhetMDPP_counts)
hr <- hclust(as.dist(1-cor(t(d), method="pearson")), method="complete")
mycl <- cutree(hr, h=max(hr$height/1.5))
clusterCols <- rainbow(length(unique(mycl)))
myClusterSideBar <- clusterCols[mycl]
myheatcol <- greenred(75)
heatmap.2(d, main="F. heteroclitus (MDPP population), FC < 0.5, common sig genes (padj<0.05)",
          Rowv=as.dendrogram(hr),
          cexRow=0.75,cexCol=0.8,srtCol= 90,
          adjCol = c(NA,0),offsetCol=2.5, 
          Colv=NA, dendrogram="row", 
          scale="row", col=myheatcol, 
          density.info="none", 
          trace="none", RowSideColors= myClusterSideBar)
```


```{r F. rathbuni heatmap,}
# F. rathbuni
Frath_cols <- c(Frath_FW_cols,Frath_BW_cols)
Frath_counts <- counts_table[rownames(counts_table) %in% rownames(Frath_counts_table_ann_up),]
Frath_counts <- Frath_counts[,Frath_cols]
id <-rownames(Frath_counts)
d<-as.matrix(Frath_counts)
hr <- hclust(as.dist(1-cor(t(d), method="pearson")), method="complete")
mycl <- cutree(hr, h=max(hr$height/1.5))
clusterCols <- rainbow(length(unique(mycl)))
myClusterSideBar <- clusterCols[mycl]
myheatcol <- greenred(75)
heatmap.2(d, main="F. rathbuni, FC > 0.5, common sig genes (padj<0.05)",
          Rowv=as.dendrogram(hr),
          cexRow=0.75,cexCol=0.8,srtCol= 90,
          adjCol = c(NA,0),offsetCol=2.5, 
          Colv=NA, dendrogram="row", 
          scale="row", col=myheatcol, 
          density.info="none", 
          trace="none", RowSideColors= myClusterSideBar)
Frath_counts <- counts_table[rownames(counts_table) %in% rownames(Frath_counts_table_ann_down),]
Frath_counts <- Frath_counts[,Frath_cols]
id <-rownames(Frath_counts)
d<-as.matrix(Frath_counts)
hr <- hclust(as.dist(1-cor(t(d), method="pearson")), method="complete")
mycl <- cutree(hr, h=max(hr$height/1.5))
clusterCols <- rainbow(length(unique(mycl)))
myClusterSideBar <- clusterCols[mycl]
myheatcol <- greenred(75)
heatmap.2(d, main="F. rathbuni, FC < 0.5, common sig genes (padj<0.05)",
          Rowv=as.dendrogram(hr),
          cexRow=0.75,cexCol=0.8,srtCol= 90,
          adjCol = c(NA,0),offsetCol=2.5, 
          Colv=NA, dendrogram="row", 
          scale="row", col=myheatcol, 
          density.info="none", 
          trace="none", RowSideColors= myClusterSideBar)
```


```{r F. similis heatmap,}
# F. similis
Fsim_cols <- c(Fsim_FW_cols,Fsim_BW_cols)
Fsim_counts <- counts_table[rownames(counts_table) %in% rownames(Fsim_counts_table_ann_up),]
Fsim_counts <- Fsim_counts[,Fsim_cols]
id <-rownames(Fsim_counts)
d<-as.matrix(Fsim_counts)
hr <- hclust(as.dist(1-cor(t(d), method="pearson")), method="complete")
mycl <- cutree(hr, h=max(hr$height/1.5))
clusterCols <- rainbow(length(unique(mycl)))
myClusterSideBar <- clusterCols[mycl]
myheatcol <- greenred(75)
heatmap.2(d, main="F. similis, FC > 0.5, common sig genes (padj<0.05)",
          Rowv=as.dendrogram(hr),
          cexRow=0.75,cexCol=0.8,srtCol= 90,
          adjCol = c(NA,0),offsetCol=2.5, 
          Colv=NA, dendrogram="row", 
          scale="row", col=myheatcol, 
          density.info="none", 
          trace="none", RowSideColors= myClusterSideBar)
Fsim_counts <- counts_table[rownames(counts_table) %in% rownames(Fsim_counts_table_ann_down),]
Fsim_counts <- Fsim_counts[,Fsim_cols]
id <-rownames(Fsim_counts)
d<-as.matrix(Fsim_counts)
hr <- hclust(as.dist(1-cor(t(d), method="pearson")), method="complete")
mycl <- cutree(hr, h=max(hr$height/1.5))
clusterCols <- rainbow(length(unique(mycl)))
myClusterSideBar <- clusterCols[mycl]
myheatcol <- greenred(75)
heatmap.2(d, main="F. similis, FC < 0.5, common sig genes (padj<0.05)",
          Rowv=as.dendrogram(hr),
          cexRow=0.75,cexCol=0.8,srtCol= 90,
          adjCol = c(NA,0),offsetCol=2.5, 
          Colv=NA, dendrogram="row", 
          scale="row", col=myheatcol, 
          density.info="none", 
          trace="none", RowSideColors= myClusterSideBar)
```

# Clade 2 Heatmaps

```
# Clade 2
# F. parvapinis
Fparv_cols <- c(Fparv_FW_cols,Fparv_BW_cols)
Fparv_counts <- counts_table[rownames(counts_table) %in% rownames(Fparv_counts_table_ann_up),]
Fparv_counts <- Fparv_counts[,Fparv_cols]
id <-rownames(Fparv_counts)
d<-as.matrix(Fparv_counts)
hr <- hclust(as.dist(1-cor(t(d), method="pearson")), method="complete")
mycl <- cutree(hr, h=max(hr$height/1.5))
clusterCols <- rainbow(length(unique(mycl)))
myClusterSideBar <- clusterCols[mycl]
myheatcol <- greenred(75)
heatmap.2(d, main="F. parvapinis, FC > 0.5, common sig genes (padj<0.05)",
          Rowv=as.dendrogram(hr),
          cexRow=0.75,cexCol=0.8,srtCol= 90,
          adjCol = c(NA,0),offsetCol=2.5, 
          Colv=NA, dendrogram="row", 
          scale="row", col=myheatcol, 
          density.info="none", 
          trace="none", RowSideColors= myClusterSideBar)
Fparv_counts <- counts_table[rownames(counts_table) %in% rownames(Fparv_counts_table_ann_down),]
Fparv_counts <- Fparv_counts[,Fparv_cols]
id <-rownames(Fparv_counts)
d<-as.matrix(Fparv_counts)
hr <- hclust(as.dist(1-cor(t(d), method="pearson")), method="complete")
mycl <- cutree(hr, h=max(hr$height/1.5))
clusterCols <- rainbow(length(unique(mycl)))
myClusterSideBar <- clusterCols[mycl]
myheatcol <- greenred(75)
heatmap.2(d, main="F. parvapinis, FC < 0.5, common sig genes (padj<0.05)",
          Rowv=as.dendrogram(hr),
          cexRow=0.75,cexCol=0.8,srtCol= 90,
          adjCol = c(NA,0),offsetCol=2.5, 
          Colv=NA, dendrogram="row", 
          scale="row", col=myheatcol, 
          density.info="none", 
          trace="none", RowSideColors= myClusterSideBar)
```

```{r L. goodei heatmap,}
# L. goodei
Lgod_cols <- c(Lgod_FW_cols,Lgod_BW_cols)
Lgod_counts <- counts_table[rownames(counts_table) %in% rownames(Lgod_counts_table_ann_up),]
Lgod_counts <- Lgod_counts[,Lgod_cols]
id <-rownames(Lgod_counts)
d<-as.matrix(Lgod_counts)
hr <- hclust(as.dist(1-cor(t(d), method="pearson")), method="complete")
mycl <- cutree(hr, h=max(hr$height/1.5))
clusterCols <- rainbow(length(unique(mycl)))
myClusterSideBar <- clusterCols[mycl]
myheatcol <- greenred(75)
heatmap.2(d, main="L. goodei, FC > 0.5, common sig genes (padj<0.05)",
          Rowv=as.dendrogram(hr),
          cexRow=0.75,cexCol=0.8,srtCol= 90,
          adjCol = c(NA,0),offsetCol=2.5, 
          Colv=NA, dendrogram="row", 
          scale="row", col=myheatcol, 
          density.info="none", 
          trace="none", RowSideColors= myClusterSideBar)
Lgod_counts <- counts_table[rownames(counts_table) %in% rownames(Lgod_counts_table_ann_down),]
Lgod_counts <- Lgod_counts[,Lgod_cols]
id <-rownames(Lgod_counts)
d<-as.matrix(Lgod_counts)
hr <- hclust(as.dist(1-cor(t(d), method="pearson")), method="complete")
mycl <- cutree(hr, h=max(hr$height/1.5))
clusterCols <- rainbow(length(unique(mycl)))
myClusterSideBar <- clusterCols[mycl]
myheatcol <- greenred(75)
heatmap.2(d, main="L. goodei, FC < 0.5, common sig genes (padj<0.05)",
          Rowv=as.dendrogram(hr),
          cexRow=0.75,cexCol=0.8,srtCol= 90,
          adjCol = c(NA,0),offsetCol=2.5, 
          Colv=NA, dendrogram="row", 
          scale="row", col=myheatcol, 
          density.info="none", 
          trace="none", RowSideColors= myClusterSideBar)
```


```{r L. parva heatmaps,}
# L. parva
Lpar_cols <- c(Lpar_FW_cols,Lpar_BW_cols)
Lpar_counts <- counts_table[rownames(counts_table) %in% rownames(Lpar_counts_table_ann_up),]
Lpar_counts <- Lpar_counts[,Lpar_cols]
id <-rownames(Lpar_counts)
d<-as.matrix(Lpar_counts)
hr <- hclust(as.dist(1-cor(t(d), method="pearson")), method="complete")
mycl <- cutree(hr, h=max(hr$height/1.5))
clusterCols <- rainbow(length(unique(mycl)))
myClusterSideBar <- clusterCols[mycl]
myheatcol <- greenred(75)
heatmap.2(d, main="L. parva, FC > 0.5, common sig genes (padj<0.05)",
          Rowv=as.dendrogram(hr),
          cexRow=0.75,cexCol=0.8,srtCol= 90,
          adjCol = c(NA,0),offsetCol=2.5, 
          Colv=NA, dendrogram="row", 
          scale="row", col=myheatcol, 
          density.info="none", 
          trace="none", RowSideColors= myClusterSideBar)
Lpar_counts <- counts_table[rownames(counts_table) %in% rownames(Lpar_counts_table_ann_down),]
Lpar_counts <- Lpar_counts[,Lgod_cols]
id <-rownames(Lpar_counts)
d<-as.matrix(Lpar_counts)
hr <- hclust(as.dist(1-cor(t(d), method="pearson")), method="complete")
mycl <- cutree(hr, h=max(hr$height/1.5))
clusterCols <- rainbow(length(unique(mycl)))
myClusterSideBar <- clusterCols[mycl]
myheatcol <- greenred(75)
heatmap.2(d, main="L. parva, FC < 0.5, common sig genes (padj<0.05)",
          Rowv=as.dendrogram(hr),
          cexRow=0.75,cexCol=0.8,srtCol= 90,
          adjCol = c(NA,0),offsetCol=2.5, 
          Colv=NA, dendrogram="row", 
          scale="row", col=myheatcol, 
          density.info="none", 
          trace="none", RowSideColors= myClusterSideBar)
```


# Clade 3 heatmaps

```{r A. xenica heatmaps,}
Axen_cols <- c(Axen_FW_cols,Axen_BW_cols)
Axen_counts <- counts_table[rownames(counts_table) %in% rownames(Axen_counts_table_ann_up),]
Axen_counts <- Axen_counts[,Axen_cols]
id <-rownames(Axen_counts)
d<-as.matrix(Axen_counts)
hr <- hclust(as.dist(1-cor(t(d), method="pearson")), method="complete")
mycl <- cutree(hr, h=max(hr$height/1.5))
clusterCols <- rainbow(length(unique(mycl)))
myClusterSideBar <- clusterCols[mycl]
myheatcol <- greenred(75)
heatmap.2(d, main="A. xenica, FC > 0.5, common sig genes (padj<0.05)",
          Rowv=as.dendrogram(hr),
          cexRow=0.75,cexCol=0.8,srtCol= 90,
          adjCol = c(NA,0),offsetCol=2.5, 
          Colv=NA, dendrogram="row", 
          scale="row", col=myheatcol, 
          density.info="none", 
          trace="none", RowSideColors= myClusterSideBar)
#Axen_counts <- counts_table[rownames(counts_table) %in% rownames(Axen_counts_table_ann_down),]
#Axen_counts <- Axen_counts[,Axen_cols]
#id <-rownames(Axen_counts)
#d<-as.matrix(Axen_counts)
#hr <- hclust(as.dist(1-cor(t(d), method="pearson")), method="complete")
#mycl <- cutree(hr, h=max(hr$height/1.5))
#clusterCols <- rainbow(length(unique(mycl)))
#myClusterSideBar <- clusterCols[mycl]
#myheatcol <- greenred(75)
#heatmap.2(d, main="A. xenica, FC < 0.5, common sig genes (padj<0.05)",
#          Rowv=as.dendrogram(hr),
#          cexRow=0.75,cexCol=0.8,srtCol= 90,
#          adjCol = c(NA,0),offsetCol=2.5, 
#          Colv=NA, dendrogram="row", 
#          scale="row", col=myheatcol, 
#          density.info="none", 
#          trace="none", RowSideColors= myClusterSideBar)
```

```{r F. chrysotus heatmaps,}
# F. chrysotus
Fchry_cols <- c(Fchry_FW_cols,Fchry_BW_cols)
Fchry_counts <- counts_table[rownames(counts_table) %in% rownames(Fchry_counts_table_ann_up),]
Fchry_counts <- Fchry_counts[,Fchry_cols]
id <-rownames(Fchry_counts)
d<-as.matrix(Fchry_counts)
hr <- hclust(as.dist(1-cor(t(d), method="pearson")), method="complete")
mycl <- cutree(hr, h=max(hr$height/1.5))
clusterCols <- rainbow(length(unique(mycl)))
myClusterSideBar <- clusterCols[mycl]
myheatcol <- greenred(75)
heatmap.2(d, main="F. chrysotus, FC > 0.5, common sig genes (padj<0.05)",
          Rowv=as.dendrogram(hr),
          cexRow=0.75,cexCol=0.8,srtCol= 90,
          adjCol = c(NA,0),offsetCol=2.5, 
          Colv=NA, dendrogram="row", 
          scale="row", col=myheatcol, 
          density.info="none", 
          trace="none", RowSideColors= myClusterSideBar)
Fchry_counts <- counts_table[rownames(counts_table) %in% rownames(Fchry_counts_table_ann_down),]
Fchry_counts <- Fchry_counts[,Fchry_cols]
id <-rownames(Fchry_counts)
d<-as.matrix(Fchry_counts)
hr <- hclust(as.dist(1-cor(t(d), method="pearson")), method="complete")
mycl <- cutree(hr, h=max(hr$height/1.5))
clusterCols <- rainbow(length(unique(mycl)))
myClusterSideBar <- clusterCols[mycl]
myheatcol <- greenred(75)
heatmap.2(d, main="F. chrysotus, FC < 0.5, common sig genes (padj<0.05)",
          Rowv=as.dendrogram(hr),
          cexRow=0.75,cexCol=0.8,srtCol= 90,
          adjCol = c(NA,0),offsetCol=2.5, 
          Colv=NA, dendrogram="row", 
          scale="row", col=myheatcol, 
          density.info="none", 
          trace="none", RowSideColors= myClusterSideBar)
```


```{r F. notatus heatmaps,}
# F. notatus
Fnota_cols <- c(Fnota_FW_cols,Fnota_BW_cols)
Fnota_counts <- counts_table[rownames(counts_table) %in% rownames(Fnota_counts_table_ann_up),]
Fnota_counts <- Fnota_counts[,Fnota_cols]
id <-rownames(Fnota_counts)
d<-as.matrix(Fnota_counts)
hr <- hclust(as.dist(1-cor(t(d), method="pearson")), method="complete")
mycl <- cutree(hr, h=max(hr$height/1.5))
clusterCols <- rainbow(length(unique(mycl)))
myClusterSideBar <- clusterCols[mycl]
myheatcol <- greenred(75)
heatmap.2(d, main="F. notatus, FC > 0.5, common sig genes (padj<0.05)",
          Rowv=as.dendrogram(hr),
          cexRow=0.75,cexCol=0.8,srtCol= 90,
          adjCol = c(NA,0),offsetCol=2.5, 
          Colv=NA, dendrogram="row", 
          scale="row", col=myheatcol, 
          density.info="none", 
          trace="none", RowSideColors= myClusterSideBar)
Fnota_counts <- counts_table[rownames(counts_table) %in% rownames(Fnota_counts_table_ann_down),]
Fnota_counts <- Fnota_counts[,Fnota_cols]
id <-rownames(Fnota_counts)
d<-as.matrix(Fnota_counts)
hr <- hclust(as.dist(1-cor(t(d), method="pearson")), method="complete")
mycl <- cutree(hr, h=max(hr$height/1.5))
clusterCols <- rainbow(length(unique(mycl)))
myClusterSideBar <- clusterCols[mycl]
myheatcol <- greenred(75)
heatmap.2(d, main="F. notatus, FC < 0.5, common sig genes (padj<0.05)",
          Rowv=as.dendrogram(hr),
          cexRow=0.75,cexCol=0.8,srtCol= 90,
          adjCol = c(NA,0),offsetCol=2.5, 
          Colv=NA, dendrogram="row", 
          scale="row", col=myheatcol, 
          density.info="none", 
          trace="none", RowSideColors= myClusterSideBar)
```


```{r F. olivaceus heatmaps,}
# F. olivaceus
Foli_cols <- c(Foli_FW_cols,Foli_BW_cols)
Foli_counts <- counts_table[rownames(counts_table) %in% rownames(Foli_counts_table_ann_up),]
Foli_counts <- Foli_counts[,Foli_cols]
id <-rownames(Foli_counts)
d<-as.matrix(Foli_counts)
hr <- hclust(as.dist(1-cor(t(d), method="pearson")), method="complete")
mycl <- cutree(hr, h=max(hr$height/1.5))
clusterCols <- rainbow(length(unique(mycl)))
myClusterSideBar <- clusterCols[mycl]
myheatcol <- greenred(75)
heatmap.2(d, main="F. olivaceus, FC > 0.5, common sig genes (padj<0.05)",
          Rowv=as.dendrogram(hr),
          cexRow=0.75,cexCol=0.8,srtCol= 90,
          adjCol = c(NA,0),offsetCol=2.5, 
          Colv=NA, dendrogram="row", 
          scale="row", col=myheatcol, 
          density.info="none", 
          trace="none", RowSideColors= myClusterSideBar)
#Foli_counts <- counts_table[rownames(counts_table) %in% rownames(Foli_counts_table_ann_down),]
#Foli_counts <- Foli_counts[,Foli_cols]
#id <-rownames(Foli_counts)
#d<-as.matrix(Foli_counts)
#hr <- hclust(as.dist(1-cor(t(d), method="pearson")), method="complete")
#mycl <- cutree(hr, h=max(hr$height/1.5))
#clusterCols <- rainbow(length(unique(mycl)))
#myClusterSideBar <- clusterCols[mycl]
#myheatcol <- greenred(75)
#heatmap.2(d, main="F. olivaceus, FC < 0.5, common sig genes (padj<0.05)",
#          Rowv=as.dendrogram(hr),
#          cexRow=0.75,cexCol=0.8,srtCol= 90,
#          adjCol = c(NA,0),offsetCol=2.5, 
#          Colv=NA, dendrogram="row", 
#          scale="row", col=myheatcol, 
#          density.info="none", 
#          trace="none", RowSideColors= myClusterSideBar)
```


```{r F. sciadicus heatmaps,}
# F. sciadicus
Fsci_cols <- c(Fsci_FW_cols,Fsci_BW_cols)
Fsci_counts <- counts_table[rownames(counts_table) %in% rownames(Fsci_counts_table_ann_up),]
Fsci_counts <- Fsci_counts[,Fsci_cols]
id <-rownames(Fsci_counts)
d<-as.matrix(Fsci_counts)
hr <- hclust(as.dist(1-cor(t(d), method="pearson")), method="complete")
mycl <- cutree(hr, h=max(hr$height/1.5))
clusterCols <- rainbow(length(unique(mycl)))
myClusterSideBar <- clusterCols[mycl]
myheatcol <- greenred(75)
heatmap.2(d, main="F. sciadicus, FC > 0.5, common sig genes (padj<0.05)",
          Rowv=as.dendrogram(hr),
          cexRow=0.75,cexCol=0.8,srtCol= 90,
          adjCol = c(NA,0),offsetCol=2.5, 
          Colv=NA, dendrogram="row", 
          scale="row", col=myheatcol, 
          density.info="none", 
          trace="none", RowSideColors= myClusterSideBar)
Fsci_counts <- counts_table[rownames(counts_table) %in% rownames(Fsci_counts_table_ann_down),]
Fsci_counts <- Fsci_counts[,Fsci_cols]
id <-rownames(Fsci_counts)
d<-as.matrix(Fsci_counts)
hr <- hclust(as.dist(1-cor(t(d), method="pearson")), method="complete")
mycl <- cutree(hr, h=max(hr$height/1.5))
clusterCols <- rainbow(length(unique(mycl)))
myClusterSideBar <- clusterCols[mycl]
myheatcol <- greenred(75)
heatmap.2(d, main="F. sciadicus, FC < 0.5, common sig genes (padj<0.05)",
          Rowv=as.dendrogram(hr),
          cexRow=0.75,cexCol=0.8,srtCol= 90,
          adjCol = c(NA,0),offsetCol=2.5, 
          Colv=NA, dendrogram="row", 
          scale="row", col=myheatcol, 
          density.info="none", 
          trace="none", RowSideColors= myClusterSideBar)
```


```{r F. zebrinus heatmaps,}
# F. zebrinus
Fzeb_cols <- c(Fzeb_FW_cols,Fzeb_BW_cols)
Fzeb_counts <- counts_table[rownames(counts_table) %in% rownames(Fzeb_counts_table_ann_up),]
Fzeb_counts <- Fzeb_counts[,Fzeb_cols]
id <-rownames(Fzeb_counts)
d<-as.matrix(Fzeb_counts)
hr <- hclust(as.dist(1-cor(t(d), method="pearson")), method="complete")
mycl <- cutree(hr, h=max(hr$height/1.5))
clusterCols <- rainbow(length(unique(mycl)))
myClusterSideBar <- clusterCols[mycl]
myheatcol <- greenred(75)
heatmap.2(d, main="F. zebrinus, FC > 0.5, common sig genes (padj<0.05)",
          Rowv=as.dendrogram(hr),
          cexRow=0.75,cexCol=0.8,srtCol= 90,
          adjCol = c(NA,0),offsetCol=2.5, 
          Colv=NA, dendrogram="row", 
          scale="row", col=myheatcol, 
          density.info="none", 
          trace="none", RowSideColors= myClusterSideBar)
#Fzeb_counts <- counts_table[rownames(counts_table) %in% rownames(Fzeb_counts_table_ann_down),]
#Fzeb_counts <- Fzeb_counts[,Fzeb_cols]
#id <-rownames(Fzeb_counts)
#d<-as.matrix(Fzeb_counts)
#hr <- hclust(as.dist(1-cor(t(d), method="pearson")), method="complete")
#mycl <- cutree(hr, h=max(hr$height/1.5))
#clusterCols <- rainbow(length(unique(mycl)))
#myClusterSideBar <- clusterCols[mycl]
#myheatcol <- greenred(75)
#heatmap.2(d, main="F. zebrinus, FC < 0.5, common sig genes (padj<0.05)",
#          Rowv=as.dendrogram(hr),
#          cexRow=0.75,cexCol=0.8,srtCol= 90,
#          adjCol = c(NA,0),offsetCol=2.5, 
#          Colv=NA, dendrogram="row", 
#          scale="row", col=myheatcol, 
#          density.info="none", 
#          trace="none", RowSideColors= myClusterSideBar)
```

```{r Display versions,}
sessionInfo()
```
