---
title: "full_model"
author: "Lisa K. Johnson"
date: "6/8/2018"
output: html_document
---

```{r setup, include=FALSE, echo = FALSE}
library(DESeq2)
library(RColorBrewer)
library(gplots)
library(tximport)
source('../scripts/plotPCAWithSampleNames.R')
source('../scripts/overLapper_original.R')
```

# DE by all species (full model)

```{r, echo = FALSE}
setwd("~/Documents/UCDavis/Whitehead/RNAseq_15killifish/DE_scripts")
dir="../salmon_denovo_by_species"
files_list = list.files("../salmon_denovo_by_species/")
files_list
#gene_names_list = list.files("~/Documents/UCDavis/Whitehead/annotation_files_test/")

#gene_names_list
for (species in files_list){
  species_files = paste("../salmon_denovo_by_species/",species,sep="")
  species_files_list = list.files(species_files)
  print(species_files)
  print(species_files_list)
  files <- file.path(dir,species,species_files_list,"quant.sf")
  files
  print(file.exists(files))
  #contigs_file = paste("~/Documents/UCDavis/Whitehead/trinity_contig_gene_tables/",species,sep="")
  #contigs = read.csv(paste(contigs_file,"_trinity_contig_gene_table.txt",sep=""))
  #print(dim(contigs))
  gene_names_file = paste("~/Documents/UCDavis/Whitehead/counts_collapsed_July2019/",species,sep="")
  gene_names <- read.csv(paste(gene_names_file,"_contig_gene.csv",sep=""))
  print(dim(gene_names))
  gene_names_id <- gene_names[,c(2,3)]
  tx2gene <- gene_names_id
  txi.salmon <- tximport(files, type = "salmon", tx2gene = tx2gene)
  print(dim(txi.salmon$counts))
  counts <- txi.salmon$counts
  colnames(counts) <- species_files_list
  head(counts)
  #gene <- rownames(counts)
  #counts <- cbind(gene,counts)
  #counts <- as.data.frame(counts)
  #colnames(gene_names)<-c("index","contig","seqid","start","end","length","NCBI.id","NCBI.protein","Notes","NCBI.transcript","NCBI.product","gene","NCBI.gene")
  #counts <- merge(gene_names,counts,by="gene")
  counts_matrix = paste("~/Documents/UCDavis/Whitehead/counts_matrices_July2019/",species,sep="")
  counts_matrix = paste(counts_matrix,"_counts.csv",sep="")
  write.csv(counts,counts_matrix)
}

```