
---
title: "RNAseq, DE analysis for F_similis killifish osmotic challenge"
author: "Lisa K. Johnson"
date: '`r Sys.Date()`'
output:
  html_document:
    code_folding: hide
    collapsed: no
    df_print: paged
    number_sections: yes
    theme: cerulean
    toc: yes
    toc_depth: 5
    toc_float: yes
---


```{r LoadPackages, results='hide', include=FALSE}
packages<-function(x){
  x<-as.character(match.call()[[2]])
  if (!require(x,character.only=TRUE)){
    install.packages(pkgs=x,repos="http://cran.r-project.org")
    require(x,character.only=TRUE)
  }
}
bioconductors <- function(x){
    x<- as.character(match.call()[[2]])
    if (!require(x, character.only = TRUE)){
      source("https://bioconductor.org/biocLite.R")
      biocLite(pkgs=x)
      require(x, character.only = TRUE)
    }
}
packages("RColorBrewer")
packages("pheatmap")
packages("vsn")
packages(pheatmap)
packages(cowplot)
# for DESeq
packages(lattice)
packages(RColorBrewer)
packages(dplyr)
packages(tidyr)
packages(gplots)
packages(ggplot2)
bioconductors(DESeq2)
bioconductors(tximport)
bioconductors(biomaRt)
```


```{r load custom scripts and data, results='hide', include=FALSE}
if(!file.exists('plotPCAWithSampleNames.R')){
  download.file('https://gist.githubusercontent.com/ljcohen/d6cf3367efae60d7fa1ea383fd7a1296/raw/f11030ced8c7953be6fada0325b92c20d369e0a7/plotPCAWithSampleNames.R', 'plotPCAWithSampleNames.R')
	}
source('plotPCAWithSampleNames.R')
if(!file.exists('overLapper_original.R')){
  download.file("https://gist.githubusercontent.com/ljcohen/b7e5fa93b8b77c33d26e4c44cadb5bb7/raw/3a2f84be2e937ef721cafaf308ff6456168f30d9/overLapper_original.R",'overLapper_original.R')
	}
source('overLapper_original.R')
# This is just the counts with Experimental Design Info in the last 5 rows
if(!file.exists('../../Ensembl_species_counts_designfactors.csv')){
  download.file("https://osf.io/7vp38/download",'../../Ensembl_species_counts_designfactors.csv')
	}
counts_design <- read.csv("../../Ensembl_species_counts_designfactors.csv",stringsAsFactors = FALSE)
```


```{r format counts and ExpDesign, include=FALSE, results='hide'}
design <- counts_design[counts_design$Ensembl == 'Empty',]
#design$type <- c("species","native_salinity","clade","group","condition")
drops <- c("X","Ensembl",
           "F_zebrinus_BW_1.quant","F_zebrinus_BW_2.quant",
           "F_zebrinus_FW_1.quant","F_zebrinus_FW_2.quant",
           "F_notti_FW_1.quant","F_notti_FW_2.quant")
counts<-counts_design[!counts_design$Ensembl == 'Empty',]
rownames(counts)<-counts$Ensembl
design <- design[ , !(names(design) %in% drops)]
counts <- counts[ , !(names(counts) %in% drops)]
design <- design[ , startsWith(names(design),"F_similis")]
counts <- counts[ , startsWith(names(counts),"F_similis")]
dim(design)
dim(counts)
# design cateogories (full)
species<-as.character(unlist(design[1,]))
nativephysiology<-as.character(unlist(design[2,]))
clade<-as.character(unlist(design[3,]))
condition<-as.character(unlist(design[5,]))
cols<-colnames(counts)
ExpDesign <- data.frame(row.names=cols,
                        condition=condition)
ExpDesign
```


# Filtering counts

The following shows the dimensions of the dataframe when we filter out genes with low counts.

9 samples must have a count of at least 0.1:

```{r filtering5,}
filter <- rownames(counts[rowSums(counts >= 9) >= 0.1,])
filtered_counts <- counts[filter,]
dim(filtered_counts)
```


```{r run DESeq, }
all(rownames(ExpDesign) == colnames(counts))
counts_round<- round(data.matrix(counts),digits=0)
dds <- DESeqDataSetFromMatrix(countData = counts_round,colData = ExpDesign,design = ~condition)
dds<-DESeq(dds)
matrix(resultsNames(dds))
plotDispEsts(dds)
resultsNames(dds)
vsd <- vst(dds, blind=FALSE)
meanSdPlot(assay(vsd))
plotDispEsts(dds)
plotPCA(vsd, intgroup=c("condition"))
plotPCAWithSampleNames(vsd,intgroup=c("condition"))
```

